name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icondominioapi:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'condominio-api060100' }}
      run: |
        cd ./condominio-core-api
        docker login --username=ferchu060100 --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a condominio-api060100
        heroku container:release web -a condominio-api060100